name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build AAB
        run: ./gradlew bundleRelease --warning-mode=none
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Sign AAB
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > azxabar.keystore
          jarsigner -verbose \
            -sigalg SHA256withRSA \
            -digestalg SHA-256 \
            -keystore azxabar.keystore \
            -storepass ${{ secrets.KEY_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/bundle/release/app-release.aab \
            ${{ secrets.KEY_ALIAS }}
          cp app/build/outputs/bundle/release/app-release.aab app-release-signed.aab

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: Azxabartv-AAB
          path: app-release-signed.aab
