name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/azxabar.keystore

      - name: Build Signed AAB
        run: ./gradlew bundleRelease --warning-mode=none
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: Azxabartv-AAB
          path: app/build/outputs/bundle/release/app-release.aab
